// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaHnx0ImtcSe3jyarq_V4T6UosY8Ta_QA',
    appId: '1:611436526513:web:d4f1de34fc13a1bfc65b90',
    messagingSenderId: '611436526513',
    projectId: 'smartsync-cf370',
    authDomain: 'smartsync-cf370.firebaseapp.com',
    storageBucket: 'smartsync-cf370.firebasestorage.app',
    measurementId: 'G-9ZWPXE39FM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKh5eHHC7rY5IVKDbmilg65YkD4Et_wLE',
    appId: '1:611436526513:android:9e5ca12cef6d2296c65b90',
    messagingSenderId: '611436526513',
    projectId: 'smartsync-cf370',
    storageBucket: 'smartsync-cf370.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8Nz2Lx3SXGHVNZwvbkZdokMUoGO5DsvA',
    appId: '1:611436526513:ios:69331fd4bbd0dda4c65b90',
    messagingSenderId: '611436526513',
    projectId: 'smartsync-cf370',
    storageBucket: 'smartsync-cf370.firebasestorage.app',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8Nz2Lx3SXGHVNZwvbkZdokMUoGO5DsvA',
    appId: '1:611436526513:ios:726f542fcb6c88c4c65b90',
    messagingSenderId: '611436526513',
    projectId: 'smartsync-cf370',
    storageBucket: 'smartsync-cf370.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaHnx0ImtcSe3jyarq_V4T6UosY8Ta_QA',
    appId: '1:611436526513:web:7244c1afd668b8f8c65b90',
    messagingSenderId: '611436526513',
    projectId: 'smartsync-cf370',
    authDomain: 'smartsync-cf370.firebaseapp.com',
    storageBucket: 'smartsync-cf370.firebasestorage.app',
    measurementId: 'G-GMGQB28RYR',
  );
}
