name: smartsync
description: SmartSync – BLE + Supabase smart home controller
publish_to: "none"
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.0.5
  supabase_flutter: ^2.5.0
  flutter_blue_plus: ^1.35.5
  permission_handler: ^11.3.1
  flutter_local_notifications: ^17.2.1
  timezone: ^0.9.2
  workmanager: ^0.5.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.3
  lottie: ^3.1.2
  flutter_animate: ^4.5.0
  intl: ^0.19.0
  app_links: ^6.2.0
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/tv.png
    - assets/images/bedlamp.png
    - assets/images/bulb.png
    - assets/images/ceiling_bulb.png
    - assets/images/lock.png
    - assets/images/fan.png
    - assets/images/room_header.png
