name: SmartSync
description: Smart Home UI
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  supabase_flutter: ^1.4.0
  flutter_blue_plus: ^1.3.3
  shared_preferences: ^2.1.1
  percent_indicator: ^4.2.2
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/onboarding1.png
    - assets/images/onboarding2.png
    - assets/images/room_kitchen.jpg
    - assets/images/room_dining.jpg
    - assets/images/avatar.png
