name: smartsync_app
description: Smart home automation for elderly care
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  firebase_storage: ^13.0.3
  firebase_messaging: ^16.0.3
  firebase_analytics: ^12.0.3
  
  # Bluetooth
  flutter_blue_plus: ^2.0.0
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # Navigation
  go_router: ^16.3.0
  
  # UI Components
  flutter_svg: ^2.0.9
  lottie: ^3.3.2
  percent_indicator: ^4.2.3
  syncfusion_flutter_charts: ^31.2.4
  shimmer: ^3.0.0
  
  # Utilities
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  permission_handler: ^12.0.1
  device_info_plus: ^12.2.0
  connectivity_plus: ^7.0.0
  
  # Security
  flutter_secure_storage: ^9.0.0
  
  # HTTP & JSON
  http: ^1.1.0
  dio: ^5.4.0
  json_annotation: ^4.8.1
  
  # Icons
  cupertino_icons: ^1.0.2

  smooth_page_indicator: ^1.2.1
  flutter_dotenv: ^5.1.0
  firebase_app_check: ^0.4.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/models/
    - assets/models/schedule_predictor.tflite
    - assets/models/anomaly_detector.tflite
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500