[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
monitor_port = COM12
monitor_filters = esp32_exception_decoder
monitor_dtr = 0
monitor_rts = 0

build_flags = 
    -DCORE_DEBUG_LEVEL=4
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -Ilib/SPI/src

lib_deps = 
    adafruit/DHT sensor library@^1.4.4
    adafruit/Adafruit Unified Sensor@^1.1.9
    adafruit/RTClib@^2.1.1
    bblanchon/ArduinoJson@^6.21.3
    h2zero/NimBLE-Arduino@^1.4.1
    marcoschwartz/LiquidCrystal_I2C@^1.1.2
    SPI  ; <—— THIS FIXES THE ERROR

board_build.partitions = min_spiffs.csv

debug_tool = esp-prog
debug_init_break = tbreak setup

upload_speed = 921600
upload_protocol = esptool
upload_port = COM12

[env:esp32dev_debug]
extends = env:esp32dev
build_type = debug
