name: Automated Tests

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Run unit tests
      run: echo "Running unit tests..."
    
    - name: Run integration tests
      run: echo "Running integration tests..."
